version: '3.8'

volumes:
  jenkins-data:
  jenkins-docker-certs:

services:
  jenkins:
    build: .
    image: 'jenkins'
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock